#!/bin/sh

#
# Script (daemon) to keep track of changes to NVRAM storage.
#
# Version 0.4 - Copyright (c) 2012 by RevoGirl <RevoGirl@rocketmail.com>
# Version 0.5 - Copyright (c) 2013 by Pike <PikerAlpha@yahoo.com>
#
# Updates:
#          - Injecting GUID:ROM and GUID:MLB for iMessage (PikerAlpha, January 2013)
#

#set -x # Used for tracing errors (can be put anywhere in the script).

#================================= GLOBAL VARS ==================================

#
# Insert your MAC address here!
#
ROM="%01%02%03%04%05%06"

#
# Insert your Base Board Serial # here!
#
MLB="%01%02%03%04%05%06%07%08%09%0A%0B%0C%0D%0E%0F%10%11"

GUID="4D1EDE05-38C7-4A6A-9CC6-4BCCA8B38C14"
GUID_ROM="${GUID}:ROM=${ROM}"
GUID_MLB="${GUID}:MLB=${MLB}"

product=nvramStorage

storagePlist=/Extra/NVRAM/${product}.plist

tmpStoragePlist=/tmp/${product}.plist

#=============================== LOCAL FUNCTIONS ================================

function _fileExists()
{
  if [ -f $1 ];
      then
          echo 0 # "Storage file exists"
      else
          echo 1 # "Storage file does not exist"
  fi
}

#--------------------------------------------------------------------------------

function _initialRun()
{
  echo $(_fileExists $tmpStoragePlist)
}

#--------------------------------------------------------------------------------

function _shouldUpdate()
{
  /usr/sbin/nvram -xp > $tmpStoragePlist

  local storageChecksum=`/sbin/md5 -q $storagePlist`
  local tmpStorageChecksum=`/sbin/md5 -q $tmpStoragePlist`

  if [ $storageChecksum == $tmpStorageChecksum ];
      then
          echo 0
      else
          echo 1
  fi
}

#--------------------------------------------------------------------------------

function _restoreNVRAMFromFile()
{
  /usr/sbin/nvram -xf $storagePlist
  /bin/cp $storagePlist $tmpStoragePlist
}

#--------------------------------------------------------------------------------

function _updateNVRAM()
{
  /bin/cp $tmpStoragePlist $storagePlist         
  _restoreNVRAMFromFile
}

#--------------------------------------------------------------------------------

function _iMessageData()
{
  /usr/sbin/nvram $GUID_ROM
  /usr/sbin/nvram $GUID_MLB
}

#==================================== START =====================================

if [ $(_initialRun) -eq 1 ];
    then
        echo "Restored" `/bin/date "+%d-%m-%Y @ %H:%M:%S"`

        _restoreNVRAMFromFile
        _iMessageData
    else
        echo "Checked" `/bin/date "+ @ %H:%M:%S"`

        if [ $(_shouldUpdate) -eq 1 ]; then
            echo "Update" `/bin/date "+ @ %H:%M:%S"`

            _updateNVRAM
        fi
fi

#--------------------------------------------------------------------------------

